AppBundle\Entity\Arena:
    attributes:
        id:
            groups: ['arena', 'sportcourt']
        name:
            groups: ['arena', 'sportcourt']
        address:
            groups: ['arena', 'sportcourt']
        sportcourts:
            groups: ['arena']


AppBundle\Entity\SportCourt:
    attributes:
        id:
            groups: ['arena', 'sportcourt']
        type:
            groups: ['arena', 'sportcourt']
        nbrSeats:
            groups: ['arena', 'sportcourt']
        arena:
            groups: ['sportcourt']

AppBundle\Entity\User:
    attributes:
        id:
            groups: ['user','userall', 'auth-token']
        firstname:
            groups: ['user','userall', 'auth-token']
        lastname:
            groups: ['user','userall', 'auth-token']
        email:
            groups: ['user','userall', 'auth-token']
        password:
            groups: ['userall']

AppBundle\Entity\AuthToken:
    attributes:
        id:
            groups: ['auth-token']
        value:
            groups: ['auth-token']
        createdAt:
            groups: ['auth-token']
        user:
            groups: ['auth-token']
